# Generated by Django 4.1.3 on 2022-12-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_remove_userinfo_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('typp', models.CharField(max_length=32)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
