# Generated by Django 4.1.3 on 2022-12-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_country_school_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
