# Generated by Django 4.1.3 on 2022-12-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='events',
            field=models.ManyToManyField(to='app01.event'),
        ),
    ]
