# Generated by Django 4.1.3 on 2022-12-14 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_userinfo_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=32, verbose_name='参考链接'),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.country', verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='event',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.major', verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='event',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.school', verbose_name='学校'),
        ),
    ]
