# Generated by Django 4.1.3 on 2022-12-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_remove_userinfo_events_alter_userinfo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_event',
            name='nid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.event'),
        ),
        migrations.AlterField(
            model_name='user_event',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.userinfo'),
        ),
    ]
