# Generated by Django 4.1.3 on 2022-12-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_alter_user_event_nid_alter_user_event_uid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Event',
            new_name='UserEvent',
        ),
    ]
