# Generated by Django 4.1.3 on 2022-12-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_rename_user_event_userevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='uid',
        ),
    ]
