# Generated by Django 4.1.3 on 2022-12-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_remove_userevent_nid_remove_userevent_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='nid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userevent',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
