# Generated by Django 4.1.3 on 2022-12-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_userevent_address_userevent_country_userevent_major_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEvent',
            new_name='UserList',
        ),
    ]
