# Generated by Django 4.1.3 on 2022-12-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_rename_userevent_userlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='address',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='参考链接'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='name',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='名称'),
        ),
    ]
