# Generated by Django 4.1.3 on 2022-12-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_alter_userlist_address_alter_userlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='major',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='school',
        ),
    ]
