# Generated by Django 4.1.3 on 2022-12-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_delete_userlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.IntegerField(default=10)),
                ('uid', models.IntegerField(default=10)),
            ],
        ),
    ]
