# Generated by Django 4.1.3 on 2022-12-24 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='address',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='参考链接'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.country', verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.major', verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='name',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.school', verbose_name='学校'),
        ),
    ]
