# Generated by Django 4.1.3 on 2022-12-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_userlist_address_userlist_country_userlist_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='nid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
